import type { CountyCoverage } from './types';

export const SUPPORTED_COUNTIES: CountyCoverage[] = [
  // Phase 1: CivilView Bergen + Middlesex
  {
    countyName: 'Bergen County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 48,
    adjournedCount: 31,
    medianSpread: 124500,
    depositRule: '20% certified check or cashier check payable to Sheriff of Bergen County at knockdown; balance in 30 days (N.J.S.A. 2A:61-1)',
    nextAuctionDate: 'Every Friday at 2:00 PM',
    sheriffOfficeAddress: 'Bergen County Justice Center, 10 Main Street, Hackensack, NJ 07601',
    sheriffWebsiteUrl: 'https://www.bergencountysheriff.com',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1 & N.J. Court Rule 4:65',
  },
  {
    countyName: 'Middlesex County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 39,
    adjournedCount: 24,
    medianSpread: 112000,
    depositRule: '20% certified check payable to Middlesex County Sheriff; 30 days to pay remaining 80% (N.J.S.A. 2A:61-1)',
    nextAuctionDate: 'Every Wednesday at 1:30 PM',
    sheriffOfficeAddress: 'Middlesex County Administration Building, 75 Bayard Street, New Brunswick, NJ 08901',
    sheriffWebsiteUrl: 'https://www.middlesexcountynj.gov/government/departments/sheriff-s-office',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:50-1 et seq.',
  },

  // Phase 2-4: All 17 NJ Counties
  {
    countyName: 'Essex County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 64,
    adjournedCount: 42,
    medianSpread: 148000,
    depositRule: '20% certified funds immediately at knockdown; 30 days to satisfy deed balance',
    nextAuctionDate: 'Every Tuesday at 1:30 PM',
    sheriffOfficeAddress: 'Veterans Courthouse, 50 West Market Street, Newark, NJ 07102',
    sheriffWebsiteUrl: 'https://www.essexsheriff.com',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:17-36 (Statutory Adjournments)',
  },
  {
    countyName: 'Hudson County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 33,
    adjournedCount: 19,
    medianSpread: 135000,
    depositRule: '20% certified funds or cash at gavel; balance due in 30 calendar days',
    nextAuctionDate: 'Every Thursday at 1:30 PM',
    sheriffOfficeAddress: 'Hudson County Administration Building, 595 Newark Avenue, Jersey City, NJ 07306',
    sheriffWebsiteUrl: 'https://www.hudsoncountysheriff.com',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1',
  },
  {
    countyName: 'Camden County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 52,
    adjournedCount: 35,
    medianSpread: 89000,
    depositRule: '20% certified check payable to Camden County Sheriff',
    nextAuctionDate: 'Every Wednesday at 12:00 PM',
    sheriffOfficeAddress: 'City Hall, 520 Market Street, 2nd Floor, Camden, NJ 08102',
    sheriffWebsiteUrl: 'https://www.camdencounty.com/service/sheriffs-office',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1',
  },
  {
    countyName: 'Ocean County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 41,
    adjournedCount: 22,
    medianSpread: 98000,
    depositRule: '20% certified check immediately; 30 days final payment',
    nextAuctionDate: 'Every Tuesday at 2:00 PM',
    sheriffOfficeAddress: 'Ocean County Courthouse, 118 Washington Street, Toms River, NJ 08754',
    sheriffWebsiteUrl: 'https://co.ocean.nj.us/OC/Sheriff',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1',
  },
  {
    countyName: 'Monmouth County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 37,
    adjournedCount: 18,
    medianSpread: 142000,
    depositRule: '20% certified check immediately upon gavel knockdown',
    nextAuctionDate: 'Every Monday at 2:00 PM',
    sheriffOfficeAddress: 'Monmouth County Special Services Complex, 2500 Kozloski Rd, Freehold, NJ 07728',
    sheriffWebsiteUrl: 'https://www.mcsonj.org',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1',
  },
  {
    countyName: 'Passaic County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 29,
    adjournedCount: 15,
    medianSpread: 104000,
    depositRule: '20% certified check payable to Passaic County Sheriff',
    nextAuctionDate: 'Every Tuesday at 2:00 PM',
    sheriffOfficeAddress: 'Passaic County Administration Building, 401 Grand Street, Paterson, NJ 07505',
    sheriffWebsiteUrl: 'https://www.passaiccountynj.org',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1',
  },
  {
    countyName: 'Union County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 36,
    adjournedCount: 21,
    medianSpread: 119000,
    depositRule: '20% certified bank funds at fall of gavel; 30 days deed settlement',
    nextAuctionDate: 'Every Wednesday at 2:00 PM',
    sheriffOfficeAddress: 'Union County Courthouse, 2 Broad Street, Elizabeth, NJ 07207',
    sheriffWebsiteUrl: 'https://ucnj.org/sheriff',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1',
  },
  {
    countyName: 'Morris County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 22,
    adjournedCount: 11,
    medianSpread: 155000,
    depositRule: '20% certified funds or bank cashier check at knockdown',
    nextAuctionDate: 'Every Thursday at 2:00 PM',
    sheriffOfficeAddress: 'Morris County Courthouse, Washington & Court Streets, Morristown, NJ 07963',
    sheriffWebsiteUrl: 'https://sheriff.morriscountynj.gov',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1',
  },
  {
    countyName: 'Burlington County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 31,
    adjournedCount: 17,
    medianSpread: 92000,
    depositRule: '20% certified check immediately; balance within 30 days',
    nextAuctionDate: 'Every Thursday at 12:00 PM',
    sheriffOfficeAddress: 'Courts Facility, 49 Rancocas Road, Mount Holly, NJ 08060',
    sheriffWebsiteUrl: 'https://co.burlington.nj.us/130/Sheriffs-Department',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1',
  },
  {
    countyName: 'Mercer County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 27,
    adjournedCount: 14,
    medianSpread: 108000,
    depositRule: '20% certified check immediately upon gavel strike',
    nextAuctionDate: 'Every Wednesday at 2:00 PM',
    sheriffOfficeAddress: 'Mercer County Courthouse, 175 South Broad Street, Trenton, NJ 08650',
    sheriffWebsiteUrl: 'https://www.mercercounty.org/departments/sheriff-s-office',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1',
  },
  {
    countyName: 'Gloucester County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 24,
    adjournedCount: 12,
    medianSpread: 86000,
    depositRule: '20% certified bank check payable to Gloucester County Sheriff',
    nextAuctionDate: 'Every Wednesday at 2:00 PM',
    sheriffOfficeAddress: 'Justice Complex, 70 Hunter Street, Woodbury, NJ 08096',
    sheriffWebsiteUrl: 'https://www.gloucestercountynj.gov/383/Sheriffs-Office',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1',
  },
  {
    countyName: 'Atlantic County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 30,
    adjournedCount: 19,
    medianSpread: 81000,
    depositRule: '20% certified check at conclusion of bidding',
    nextAuctionDate: 'Every Thursday at 12:00 PM',
    sheriffOfficeAddress: 'Atlantic County Criminal Courts Complex, 4997 Unami Blvd, Mays Landing, NJ 08330',
    sheriffWebsiteUrl: 'https://www.atlantic-county.org/sheriff',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1',
  },
  {
    countyName: 'Sussex County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 14,
    adjournedCount: 7,
    medianSpread: 78000,
    depositRule: '20% certified check or bank draft at hammer fall',
    nextAuctionDate: 'Every third Monday at 1:00 PM',
    sheriffOfficeAddress: 'Sussex County Judicial Center, 43-47 High Street, Newton, NJ 07860',
    sheriffWebsiteUrl: 'https://www.sussexcountysheriff.com',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1',
  },
  {
    countyName: 'Hunterdon County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 11,
    adjournedCount: 5,
    medianSpread: 121000,
    depositRule: '20% certified check; 30 days final payment',
    nextAuctionDate: 'Every other Wednesday at 1:30 PM',
    sheriffOfficeAddress: 'Hunterdon County Justice Center, 65 Park Avenue, Flemington, NJ 08822',
    sheriffWebsiteUrl: 'https://www.co.hunterdon.nj.us/sheriff.htm',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1',
  },
  {
    countyName: 'Cape May County',
    state: 'NJ',
    sourceType: 'CIVILVIEW',
    activeCount: 16,
    adjournedCount: 8,
    medianSpread: 139000,
    depositRule: '20% certified funds immediately at auction knockdown',
    nextAuctionDate: 'First Tuesday of every month at 1:00 PM',
    sheriffOfficeAddress: 'Cape May County Courthouse, 9 N Main St, Cape May Court House, NJ 08210',
    sheriffWebsiteUrl: 'https://cmcsheriff.net',
    verifiedAugust2026Statute: 'N.J.S.A. 2A:61-1',
  },

  // Pennsylvania: Philadelphia / Montgomery / Lehigh / Allegheny
  {
    countyName: 'Philadelphia County',
    state: 'PA',
    sourceType: 'OPA_PORTAL',
    activeCount: 78,
    adjournedCount: 46,
    medianSpread: 95000,
    depositRule: '10% deposit immediately via electronic Bid4Assets escrow or certified funds; 30 days to settle (Pa.R.C.P. 3135)',
    nextAuctionDate: 'First Tuesday of every month at 10:00 AM',
    sheriffOfficeAddress: 'Office of the Sheriff of Philadelphia City and County, 100 S Broad St 5th Floor, Philadelphia, PA 19110',
    sheriffWebsiteUrl: 'https://phillysheriff.com',
    verifiedAugust2026Statute: 'Pa.R.C.P. No. 3129.1 & 42 Pa.C.S. § 8152',
  },
  {
    countyName: 'Montgomery County',
    state: 'PA',
    sourceType: 'PDF_CRAWLER',
    activeCount: 28,
    adjournedCount: 14,
    medianSpread: 132000,
    depositRule: '10% certified check at knock down; balance within 10 business days',
    nextAuctionDate: 'Every third Wednesday at 1:00 PM',
    sheriffOfficeAddress: 'Montgomery County Courthouse, One Montgomery Plaza, Norristown, PA 19404',
    sheriffWebsiteUrl: 'https://www.montcopa.org/sheriff',
    verifiedAugust2026Statute: 'Pa.R.C.P. 3129.2',
  },
  {
    countyName: 'Lehigh County',
    state: 'PA',
    sourceType: 'COUNTYSUITE',
    activeCount: 21,
    adjournedCount: 9,
    medianSpread: 84000,
    depositRule: '10% down at hammer; balance in 20 calendar days',
    nextAuctionDate: 'Fourth Wednesday of month at 10:00 AM',
    sheriffOfficeAddress: 'Lehigh County Courthouse, 455 W Hamilton St, Allentown, PA 18101',
    sheriffWebsiteUrl: 'https://www.lehighcounty.org/Departments/Sheriff',
    verifiedAugust2026Statute: 'Pa.R.C.P. 3135',
  },
  {
    countyName: 'Allegheny County',
    state: 'PA',
    sourceType: 'PDF_CRAWLER',
    activeCount: 54,
    adjournedCount: 29,
    medianSpread: 74000,
    depositRule: '$2,000 or 10% (whichever is greater) certified check at auction; balance by following Friday at 10:00 AM',
    nextAuctionDate: 'First Monday of every month at 9:00 AM (Gold Room)',
    sheriffOfficeAddress: 'Allegheny County Courthouse, 436 Grant Street, Pittsburgh, PA 15219',
    sheriffWebsiteUrl: 'https://sheriffalleghenycounty.com',
    verifiedAugust2026Statute: 'Pa.R.C.P. 3129 & WPRDC Real Estate Portal Integration',
  },

  // Expansion Targets: Ohio Realauction & Texas Smart Search
  {
    countyName: 'Cuyahoga County (Cleveland)',
    state: 'OH',
    sourceType: 'REALAUCTION',
    activeCount: 62,
    adjournedCount: 26,
    medianSpread: 68000,
    depositRule: 'Deposit scale: $2,000 for judgment <$10k, $5,000 for $10k-$200k, $10,000 for >$200k via Ohio Realauction wire (O.R.C. § 2329.211)',
    nextAuctionDate: 'Every Monday at 9:00 AM Online',
    sheriffOfficeAddress: 'Justice Center, 1215 West 3rd Street, Cleveland, OH 44113',
    sheriffWebsiteUrl: 'https://cuyahoga.realforeclose.com',
    verifiedAugust2026Statute: 'Ohio Rev. Code § 2329.151 & § 2329.211',
  },
  {
    countyName: 'Travis County (Austin)',
    state: 'TX',
    sourceType: 'TEXAS_SMART_SEARCH',
    activeCount: 34,
    adjournedCount: 16,
    medianSpread: 162000,
    depositRule: '100% cash or cashier check by 4:00 PM day of sale payable to Travis County Constable Precinct 5 (Tex. Tax Code § 34.01)',
    nextAuctionDate: 'First Tuesday of every month at 10:00 AM',
    sheriffOfficeAddress: 'Travis County Courthouse Steps / 1000 Guadalupe St, Austin, TX 78701',
    sheriffWebsiteUrl: 'https://www.traviscountytx.gov/constables/precinct-5',
    verifiedAugust2026Statute: 'Tex. Tax Code § 34.01 & Tex. Civ. Prac. & Rem. Code § 34.041',
  },
];

export const COUNTY_COVERAGE_REGISTRY = SUPPORTED_COUNTIES;

export function getCountyCoverage(countyName: string): CountyCoverage | undefined {
  return SUPPORTED_COUNTIES.find(
    (c) => c.countyName.toLowerCase().includes(countyName.toLowerCase()) || countyName.toLowerCase().includes(c.countyName.toLowerCase())
  );
}

export function isCountySupported(countyName: string): boolean {
  return !!getCountyCoverage(countyName);
}

