import type { SheriffGovSale } from './types';

export const SHERIFF_GOV_SALES: SheriffGovSale[] = [
  // 1. CivilView Bergen County, NJ (Phase 1)
  {
    id: 'sgs-nj-bergen-f-014281-24',
    caseNumber: 'F-014281-24',
    sheriffNumber: '24003891',
    saleType: 'sheriff_foreclosure',
    jurisdictionState: 'NJ',
    county: 'Bergen County, NJ',
    court: 'Superior Court of New Jersey, Chancery Division, Bergen County',
    auctionDate: '2026-09-25',
    auctionTime: '2:00 PM EDT',
    auctionPlatform: 'CivilView / Bergen County Sheriff Live Auction',
    auctionUrl: 'https://www.civilview.com/bergen',
    depositRequirement: '20% certified bank check or cashier check payable to Sheriff of Bergen County at knockdown; 30 days to close',
    depositPercent: 20,
    parcel: {
      address: '184 Clinton Place',
      city: 'Hackensack',
      state: 'NJ',
      zip: '07601',
      coordinates: [-74.0435, 40.8859],
      livingSqft: 2240,
      bedrooms: 4,
      bathrooms: 2.5,
      lotSizeAcres: 0.16,
      yearBuilt: 1952,
      propertyType: 'Single Family Colonial',
      block: '304',
      lot: '12',
    },
    legalProse: {
      rawNoticeText: `SUPERIOR COURT OF NEW JERSEY, CHANCERY DIVISION, BERGEN COUNTY. DOCKET NO. F-014281-24. SHERIFF'S FILE NO. 24003891. U.S. BANK TRUST NATIONAL ASSOCIATION AS TRUSTEE FOR LSF9 MASTER PARTICIPATION TRUST, PLAINTIFF VS. SALVATORE DIGIROLAMO AND MARIA DIGIROLAMO, DEFENDANTS. WRIT OF EXECUTION DATED JUNE 18, 2026 FOR SALE OF MORTGAGED PREMISES. BY VIRTUE OF THE AFORESAID WRIT TO ME DIRECTED, I SHALL EXPOSE FOR SALE AT PUBLIC VENUE ON FRIDAY, SEPTEMBER 25, 2026 AT 2:00 P.M. IN THE BERGEN COUNTY JUSTICE CENTER, 10 MAIN STREET, HACKENSACK, NJ: ALL THAT CERTAIN TRACT OF LAND KNOWN AS LOT 12, BLOCK 304 ON THE OFFICIAL TAX MAP OF THE CITY OF HACKENSACK, COMMONLY KNOWN AS 184 CLINTON PLACE, HACKENSACK, NJ 07601. APPROXIMATE JUDGMENT AMOUNT: $324,850.00 TOGETHER WITH INTEREST AND COSTS. SURPLUS MONEY: IF AFTER THE SALE THERE REMAINS ANY SURPLUS MONEY, IT WILL BE DEPOSITED INTO THE SUPERIOR COURT TRUST FUND. THE SHERIFF RESERVES THE RIGHT TO ADJOURN THIS SALE WITHOUT FURTHER PUBLICATION.`,
      plaintiff: 'U.S. BANK TRUST NATIONAL ASSOCIATION AS TRUSTEE FOR LSF9 MASTER PARTICIPATION TRUST',
      defendant: 'SALVATORE DIGIROLAMO AND MARIA DIGIROLAMO',
      caseNumber: 'F-014281-24',
      courtDocket: 'CivilView Docket F-014281-24 (Bergen County Chancery)',
      statute: 'N.J.S.A. 2A:61-1 & N.J. Court Rule 4:65',
      writExecutionDate: '2026-06-18',
      finalJudgmentAmount: 324850,
      statutoryRedemption: {
        periodDays: 10,
        rule: '10-day statutory objection period under N.J. Court Rule 4:65-5. Mortgagor may file objections or redeem property by paying full judgment prior to deed issuance.',
        citation: 'N.J. Court Rule 4:65-5 (Objections to Sale)',
        equityProtectionNote: 'Debtor has exhausted one of two statutory 30-day adjournments under N.J.S.A. 2A:17-36. 1 adjournment remains.',
      },
      seniorLiens: {
        delinquentPropertyTaxes: 4820,
        municipalAssessments: 1240,
        codeEnforcementFines: 0,
        seniorMortgageStatus: 'FORECLOSING_SENIOR',
        survivingSeniorAmount: 6060,
        totalSeniorBurden: 6060,
        notes: 'Foreclosing mortgage is 1st recorded priority. Surviving liabilities are Hackensack municipal water/sewer ($1,240) and 2025 Q4 delinquent taxes ($4,820). Junior HELOC held by TD Bank wiped upon deed delivery.',
      },
      titleCloudRisk: 'LOW',
    },
    openData: {
      apn: '0223-0304-00012',
      countyAppraiserMarketValue: 565000,
      countyAssessedValue: 409400,
      annualAdValoremTax: 12888,
      delinquentTaxYears: [2025],
      delinquentTaxTotal: 4820,
      lastDeedDate: '2004-11-12',
      lastDeedPrice: 385000,
      deedBookPage: 'Book 8920, Page 314',
      zoningCode: 'R-1',
      zoningDescription: 'Single-Family Residential High Density',
      legalLotDescription: 'LOT 12, BLOCK 304, CITY OF HACKENSACK, BERGEN COUNTY, NJ',
      floodZone: 'Zone X (Minimal Flood Hazard)',
      openDataLicense: 'NJ Office of GIS Open Data Commons / CC-BY-4.0',
      primaryPortalUrl: 'https://njogis-newjersey.opendata.arcgis.com',
    },
    openImagery: {
      aerialSource: 'USDA NAIP 0.6m Multi-Spectral Aerial Ortho (Leaf-Off)',
      imageryDate: 'August 2026 Flyover',
      resolutionMeters: 0.6,
      roofWearScore: 78,
      roofType: 'Asphalt Architectural Shingle (Minor granule loss north pitch)',
      structuralIntegrityRating: 'EXCELLENT',
      lotAccessStatus: 'DEDICATED_PUBLIC_ROAD',
      imageryObservations: [
        'Roof ridge lines are straight and un-sagged; asphalt shingle age estimated 8-10 years.',
        'Backyard perimeter fenced with detached 1-car garage in sound structural condition.',
        'No visible foundation stepping cracks or ponding on driveway asphalt.',
      ],
    },
    aiWorkforce: {
      legalProseReader: {
        agentName: 'LexForeclose Legal Counsel AI',
        verdict: 'CLEAR TO BID: Senior Foreclosure with standard 10-day NJ redemption window.',
        titleRiskGrade: 'A',
        clearedForBidding: true,
        statutorySummary: 'Verified N.J.S.A. 2A:61-1 procedural compliance. Defendant served via personal delivery. No federal IRS 120-day redemption cloud.',
      },
      openDataCorrelator: {
        agentName: 'Cadastre & Macro Analyst AI',
        submarketMedianArv: 585000,
        submarketPricePerSqft: 261,
        compsAnalyzed: 8,
        assessmentRatio: 0.7245,
        taxDelinquencyWarning: 'Municipal delinquent tax total: $4,820. Must be satisfied post-sale at City Hall.',
      },
      openImageryInspector: {
        agentName: 'NAIP Computer Vision Aerial Surveyor',
        estimatedCurbAppealRating: 8,
        structuralRiskLevel: 'LOW',
        exteriorRehabMultiplier: 1.05,
        aerialFlags: ['Minor gutter cleaning needed', 'Driveway sealcoat recommended'],
      },
      dealUnderwriter: {
        agentName: 'Distress Underwriter AI',
        modeledArv: 585000,
        modeledRehabCost: 38000,
        holdingAndClosingCosts: 24500,
        minimumUpsetBid: 195000,
        maximumAllowableBid: 347000,
        expectedGrossProfit: 175500,
        expectedNetMarginPct: 29.8,
        perfectScore: 92,
        riskTier: 'RING_1_PRIORITY',
        executiveSummary: 'Premier Hackensack suburban flip. 4-bedroom Colonial with $175k equity cushion beneath conservative 70% rule ceiling.',
      },
    },
    outcomesLedger: {
      saleId: 'sgs-nj-bergen-f-014281-24',
      address: '184 Clinton Place, Hackensack, NJ',
      county: 'Bergen County, NJ',
      auctionDate: '2026-09-25',
      predictedArv: 585000,
      predictedMaxBid: 347000,
      actualWinningBid: 0,
      variancePct: 0,
      outcome: 'WIN',
      learningFactorApplied: 1.018,
      weeklyCalibrationInsight: 'Bergen County suburban inventory showing 1.018x appreciation premium over Q2 median ARVs.',
    },
    verifiedAugust2026: true,

    // Build Sequence: NJ Equalization Table
    njEqualization: {
      municipality: 'Hackensack',
      county: 'Bergen',
      directorsRatio: 0.7245,
      commonLevelRange: [0.6158, 0.8332],
      equalizedTrueMarketValue: 565080,
      taxRatePerHundred: 3.148,
    },

    // Build Sequence: Entity Resolution (Hack 3)
    entityResolution: {
      rawEntityName: 'U.S. BANK TRUST NATIONAL ASSOCIATION AS TRUSTEE FOR LSF9 MASTER PARTICIPATION TRUST',
      trueBeneficialOwner: 'Lone Star Funds / Hudson Advisors LP (Dallas, TX)',
      loanServicer: 'Caliber Home Loans / Newrez LLC',
      plaintiffCounselFirm: 'Fein, Such, Kahn & Shepard, P.C. (Parsippany, NJ)',
      foreclosureCounselContact: '(973) 538-4700 / foreclosure@feinsuch.com',
    },

    // Build Sequence: Daily Status Capture (Hack 9)
    dailyStatus: {
      currentStatus: 'ACTIVE_SCHEDULED',
      lastStatusCheck: '2026-09-06T08:30:00Z',
      statutoryAdjournmentCount: 1,
      adjournmentHistory: [
        { date: '2026-08-21', requestedBy: 'Defendant', reason: 'First Statutory 30-Day Adjournment pursuant to N.J.S.A. 2A:17-36' },
      ],
      bankruptcyStayActive: false,
    },

    // Build Sequence: The Four Listing Panels
    compsAndMargin: {
      recentComps: [
        { address: '162 Clinton Pl, Hackensack', saleDate: '2026-07-10', salePrice: 592000, sqft: 2280, pricePerSqft: 259, distanceMiles: 0.12, condition: 'Renovated' },
        { address: '201 Summit Ave, Hackensack', saleDate: '2026-06-18', salePrice: 579000, sqft: 2190, pricePerSqft: 264, distanceMiles: 0.28, condition: 'Good' },
        { address: '95 Linden St, Hackensack', saleDate: '2026-05-29', salePrice: 605000, sqft: 2350, pricePerSqft: 257, distanceMiles: 0.41, condition: 'Turnkey' },
      ],
      submarketMedianPpsf: 261,
      modeledRehabTier: 'MEDIUM_UPDATE',
      modeledRehabEstimate: 38000,
      holdingAndCarryingCosts: 24500,
      maximumAllowableBid: 347000,
      netSpreadDollars: 175500,
      netMarginPercent: 29.8,
    },

    flipScoreAndEndGame: {
      flipScore: 92,
      estimatedTurnaroundDays: 105,
      fixAndFlipIrr: 28.4,
      brrrrRentalYield: 9.8,
      wholetailMargin: 95000,
      recommendedExitStrategy: 'FIX_AND_FLIP',
      sensitivityMatrix: [
        { discountPct: 40, purchaseBid: 351000, projectedRoi: 31.2 },
        { discountPct: 45, purchaseBid: 321750, projectedRoi: 38.6 },
        { discountPct: 50, purchaseBid: 292500, projectedRoi: 47.1 },
      ],
    },

    resaleDemandMeter: {
      submarketAbsorptionRateMonths: 1.4,
      averageDaysOnMarket: 19,
      buyerLiquidityIndex: 94,
      schoolDistrictRating: 8,
      demandVerdict: 'EXTREME_SELLER_MARKET',
    },

    theCatch: {
      seniorSurvivingLiens: [
        { type: 'Municipal Water & Sewer', holder: 'City of Hackensack Water Utility', amount: 1240, survivesSale: true, legalBasis: 'N.J.S.A. 40:14B-42 (Super-priority municipal utility lien)' },
        { type: 'Delinquent Real Estate Taxes', holder: 'Bergen County Tax Collector', amount: 4820, survivesSale: true, legalBasis: 'N.J.S.A. 54:5-6 (First paramount lien on land)' },
      ],
      municipalTaxCertificate: { hasCertificate: false },
      codeViolations: [],
      irsRedemptionPeriodDays: 0,
      occupancyStatus: 'OWNER_OCCUPIED_EVICTION_REQ',
      overallTitleCloudRisk: 'PRISTINE_INSURABLE',
    },

    // Build Sequence: Assisted Lien Check (Hack 8)
    assistedLienCheck: {
      waterfall: [
        { position: 1, lienHolder: 'City of Hackensack (Taxes & Water)', originalAmount: 6060, currentBalance: 6060, recordingDate: '2025-10-01', lienType: 'MUNICIPAL_TAX', survivesSale: true, justification: 'N.J.S.A. 54:5-6 super-priority tax lien' },
        { position: 2, lienHolder: 'U.S. Bank Trust (LSF9 Master Trust) 1st Mortgage', originalAmount: 310000, currentBalance: 324850, recordingDate: '2004-11-12', lienType: 'FIRST_MORTGAGE', survivesSale: false, justification: 'Foreclosing senior plaintiff being satisfied by sale proceeds' },
        { position: 3, lienHolder: 'TD Bank, N.A. (Home Equity Line of Credit)', originalAmount: 50000, currentBalance: 39120, recordingDate: '2016-04-20', lienType: 'SECOND_HELOC', survivesSale: false, justification: 'Junior encumbrance extinguished upon delivery of sheriff deed' },
      ],
      totalSurvivingDebtRequired: 6060,
      safeMaxBidAfterSurvivingDebt: 340940,
    },

    // Build Sequence: Bid Card
    bidCard: {
      caseNumber: 'F-014281-24',
      sheriffNumber: '24003891',
      propertyAddress: '184 Clinton Place, Hackensack, NJ 07601',
      auctionDateTime: 'Friday, September 25, 2026 at 2:00 PM',
      sheriffSaleLocation: 'Bergen County Justice Center, 10 Main St, Hackensack, NJ',
      requiredDepositPercent: 20,
      requiredDepositDollars: 68188,
      openingBid: 1000,
      plaintiffUpsetLimit: 295000,
      ceilingBidHardStop: 340940,
      checklist: [
        { item: 'Bring 20% certified funds ($68,188 minimum) payable to "Sheriff of Bergen County"', checked: true },
        { item: 'Verify PACER docket 30 minutes prior to sale to confirm no last-minute bankruptcy stay', checked: true, warning: 'Defendant used 1 statutory adjournment already' },
        { item: 'Budget $6,060 for municipal taxes and water liens to be settled at Hackensack City Hall', checked: true },
        { item: 'Plan for writ of possession eviction filing post-confirmation if occupants do not vacate', checked: true },
      ],
    },
  },

  // 2. CivilView Middlesex County, NJ (Phase 1)
  {
    id: 'sgs-nj-middlesex-f-008914-24',
    caseNumber: 'F-008914-24',
    sheriffNumber: '24001928',
    saleType: 'sheriff_foreclosure',
    jurisdictionState: 'NJ',
    county: 'Middlesex County, NJ',
    court: 'Superior Court of New Jersey, Chancery Division, Middlesex County',
    auctionDate: '2026-09-23',
    auctionTime: '1:30 PM EDT',
    auctionPlatform: 'CivilView / Middlesex County Sheriff Live Auction',
    auctionUrl: 'https://www.civilview.com/middlesex',
    depositRequirement: '20% certified check payable to Middlesex County Sheriff; 30 days to close',
    depositPercent: 20,
    parcel: {
      address: '42 Plainfield Ave',
      city: 'Edison',
      state: 'NJ',
      zip: '08817',
      coordinates: [-74.4121, 40.5284],
      livingSqft: 1980,
      bedrooms: 4,
      bathrooms: 2,
      lotSizeAcres: 0.21,
      yearBuilt: 1964,
      propertyType: 'Single Family Split Level',
      block: '114.B',
      lot: '8',
    },
    legalProse: {
      rawNoticeText: `SUPERIOR COURT OF NEW JERSEY, CHANCERY DIVISION, MIDDLESEX COUNTY. DOCKET NO. F-008914-24. SHERIFF'S FILE NO. 24001928. WILMINGTON SAVINGS FUND SOCIETY, FSB D/B/A CHRISTIANA TRUST AS TRUSTEE, PLAINTIFF VS. GURPREET SINGH ET AL., DEFENDANTS. BY VIRTUE OF A WRIT OF EXECUTION TO ME DIRECTED, I SHALL EXPOSE TO SALE AT PUBLIC VENUE ON WEDNESDAY, SEPTEMBER 23, 2026 AT 1:30 P.M. AT THE MIDDLESEX COUNTY ADMINISTRATION BUILDING, 75 BAYARD STREET, 1ST FLOOR, NEW BRUNSWICK, NJ: ALL THAT LOT OR PARCEL OF LAND SITUATE IN THE TOWNSHIP OF EDISON, COUNTY OF MIDDLESEX, KNOWN AS LOT 8, BLOCK 114.B ON THE TAX MAP, COMMONLY KNOWN AS 42 PLAINFIELD AVE, EDISON, NJ 08817. JUDGMENT AMOUNT: $298,400.00. UPSET BID ESTIMATE: $280,000.00. CASH OR CERTIFIED CHECK FOR 20% OF PURCHASE PRICE REQUIRED AT FALL OF GAVEL.`,
      plaintiff: 'WILMINGTON SAVINGS FUND SOCIETY, FSB D/B/A CHRISTIANA TRUST AS TRUSTEE',
      defendant: 'GURPREET SINGH ET AL.',
      caseNumber: 'F-008914-24',
      courtDocket: 'CivilView Docket F-008914-24 (Middlesex County Chancery)',
      statute: 'N.J.S.A. 2A:50-1 et seq.',
      writExecutionDate: '2026-05-14',
      finalJudgmentAmount: 298400,
      statutoryRedemption: {
        periodDays: 10,
        rule: '10-day objection period under Rule 4:65-5. Sheriff deed executed upon expiration of 10 days without objection.',
        citation: 'N.J. Court Rule 4:65-5',
        equityProtectionNote: 'All statutory adjournments exhausted. Auction is peremptory.',
      },
      seniorLiens: {
        delinquentPropertyTaxes: 3410,
        municipalAssessments: 0,
        codeEnforcementFines: 0,
        seniorMortgageStatus: 'FORECLOSING_SENIOR',
        survivingSeniorAmount: 3410,
        totalSeniorBurden: 3410,
        notes: 'Senior mortgage foreclosing. $3,410 municipal real estate taxes survive. Clear title insurable by Stewart Title.',
      },
      titleCloudRisk: 'LOW',
    },
    openData: {
      apn: '12-00114-0000-00008',
      countyAppraiserMarketValue: 535000,
      countyAssessedValue: 401800,
      annualAdValoremTax: 11105,
      delinquentTaxYears: [2025],
      delinquentTaxTotal: 3410,
      lastDeedDate: '2011-03-18',
      lastDeedPrice: 320000,
      deedBookPage: 'Book 6214, Page 112',
      zoningCode: 'R-BB',
      zoningDescription: 'Single Family Residential Medium Density',
      legalLotDescription: 'LOT 8, BLOCK 114.B, TOWNSHIP OF EDISON, MIDDLESEX COUNTY, NJ',
      floodZone: 'Zone X (Unshaded)',
      openDataLicense: 'NJ Office of GIS Open Data Commons',
      primaryPortalUrl: 'https://www.middlesexcountynj.gov/government/departments/sheriff-s-office',
    },
    openImagery: {
      aerialSource: 'USDA NAIP 0.6m Ortho Aerial High-Resolution',
      imageryDate: 'August 2026 Flyover',
      resolutionMeters: 0.6,
      roofWearScore: 82,
      roofType: 'Timberline 30-Year Architectural Shingle',
      structuralIntegrityRating: 'EXCELLENT',
      lotAccessStatus: 'DEDICATED_PUBLIC_ROAD',
      imageryObservations: [
        'Roof in top 15% condition for neighborhood. Intact chimney flashing.',
        'Concrete driveway with parking for 4 vehicles.',
        'Spacious backyard with mature shade trees away from roof drip line.',
      ],
    },
    aiWorkforce: {
      legalProseReader: {
        agentName: 'LexForeclose Legal Counsel AI',
        verdict: 'PEREMPTORY AUCTION: High priority. All debtor adjournments used.',
        titleRiskGrade: 'A',
        clearedForBidding: true,
        statutorySummary: 'Clean Chancery judgment decree. Notice published in Home News Tribune 4 consecutive weeks.',
      },
      openDataCorrelator: {
        agentName: 'Cadastre & Macro Analyst AI',
        submarketMedianArv: 545000,
        submarketPricePerSqft: 275,
        compsAnalyzed: 9,
        assessmentRatio: 0.751,
        taxDelinquencyWarning: 'Current tax delinquency $3,410 to be reimbursed at closing.',
      },
      openImageryInspector: {
        agentName: 'NAIP Computer Vision Aerial Surveyor',
        estimatedCurbAppealRating: 9,
        structuralRiskLevel: 'LOW',
        exteriorRehabMultiplier: 1.0,
        aerialFlags: ['Exterior vinyl siding intact', 'No structural modifications observed'],
      },
      dealUnderwriter: {
        agentName: 'Distress Underwriter AI',
        modeledArv: 545000,
        modeledRehabCost: 32000,
        holdingAndClosingCosts: 21500,
        minimumUpsetBid: 180000,
        maximumAllowableBid: 328000,
        expectedGrossProfit: 163500,
        expectedNetMarginPct: 30.0,
        perfectScore: 94,
        riskTier: 'RING_1_PRIORITY',
        executiveSummary: 'North Edison train station commuter corridor. Split-level in high demand school district. Projected $163k equity margin.',
      },
    },
    outcomesLedger: {
      saleId: 'sgs-nj-middlesex-f-008914-24',
      address: '42 Plainfield Ave, Edison, NJ',
      county: 'Middlesex County, NJ',
      auctionDate: '2026-09-23',
      predictedArv: 545000,
      predictedMaxBid: 328000,
      actualWinningBid: 0,
      variancePct: 0,
      outcome: 'WIN',
      learningFactorApplied: 1.014,
      weeklyCalibrationInsight: 'Edison Township single-family transactions closing 3.2% above initial list price due to NYC transit connectivity.',
    },
    verifiedAugust2026: true,

    // Build Sequence: NJ Equalization Table
    njEqualization: {
      municipality: 'Edison',
      county: 'Middlesex',
      directorsRatio: 0.751,
      commonLevelRange: [0.6383, 0.8637],
      equalizedTrueMarketValue: 535020,
      taxRatePerHundred: 2.764,
    },

    // Build Sequence: Entity Resolution (Hack 3)
    entityResolution: {
      rawEntityName: 'WILMINGTON SAVINGS FUND SOCIETY, FSB D/B/A CHRISTIANA TRUST AS TRUSTEE',
      trueBeneficialOwner: 'Pretium Residential Credit Fund / Pretium Partners (New York, NY)',
      loanServicer: 'Selene Finance LP (Dallas, TX)',
      plaintiffCounselFirm: 'Robertson, Anschutz, Schneid, Crane & Partners, PLLC',
      foreclosureCounselContact: '(561) 241-6901 / mail@raslg.com',
    },

    // Build Sequence: Daily Status Capture (Hack 9)
    dailyStatus: {
      currentStatus: 'ACTIVE_SCHEDULED',
      lastStatusCheck: '2026-09-06T08:30:00Z',
      statutoryAdjournmentCount: 2,
      adjournmentHistory: [
        { date: '2026-07-15', requestedBy: 'Defendant', reason: 'First Statutory Adjournment' },
        { date: '2026-08-19', requestedBy: 'Defendant', reason: 'Second and Final Statutory Adjournment' },
      ],
      bankruptcyStayActive: false,
    },

    // Build Sequence: The Four Listing Panels
    compsAndMargin: {
      recentComps: [
        { address: '58 Plainfield Ave, Edison', saleDate: '2026-08-02', salePrice: 552000, sqft: 2010, pricePerSqft: 274, distanceMiles: 0.08, condition: 'Renovated' },
        { address: '19 Central Ave, Edison', saleDate: '2026-06-25', salePrice: 539000, sqft: 1940, pricePerSqft: 277, distanceMiles: 0.22, condition: 'Good' },
        { address: '110 Wooding Ave, Edison', saleDate: '2026-05-14', salePrice: 560000, sqft: 2040, pricePerSqft: 274, distanceMiles: 0.35, condition: 'Turnkey' },
      ],
      submarketMedianPpsf: 275,
      modeledRehabTier: 'LIGHT_COSMETIC',
      modeledRehabEstimate: 32000,
      holdingAndCarryingCosts: 21500,
      maximumAllowableBid: 328000,
      netSpreadDollars: 163500,
      netMarginPercent: 30.0,
    },

    flipScoreAndEndGame: {
      flipScore: 94,
      estimatedTurnaroundDays: 95,
      fixAndFlipIrr: 32.1,
      brrrrRentalYield: 10.4,
      wholetailMargin: 110000,
      recommendedExitStrategy: 'FIX_AND_FLIP',
      sensitivityMatrix: [
        { discountPct: 40, purchaseBid: 327000, projectedRoi: 33.4 },
        { discountPct: 45, purchaseBid: 299750, projectedRoi: 41.2 },
        { discountPct: 50, purchaseBid: 272500, projectedRoi: 50.8 },
      ],
    },

    resaleDemandMeter: {
      submarketAbsorptionRateMonths: 1.2,
      averageDaysOnMarket: 14,
      buyerLiquidityIndex: 96,
      schoolDistrictRating: 9,
      demandVerdict: 'EXTREME_SELLER_MARKET',
    },

    theCatch: {
      seniorSurvivingLiens: [
        { type: 'Delinquent Municipal Taxes', holder: 'Edison Township Tax Collector', amount: 3410, survivesSale: true, legalBasis: 'N.J.S.A. 54:5-6' },
      ],
      municipalTaxCertificate: { hasCertificate: false },
      codeViolations: [],
      irsRedemptionPeriodDays: 0,
      occupancyStatus: 'VACANT_CONFIRMED',
      overallTitleCloudRisk: 'PRISTINE_INSURABLE',
    },

    // Build Sequence: Assisted Lien Check (Hack 8)
    assistedLienCheck: {
      waterfall: [
        { position: 1, lienHolder: 'Edison Township (Ad Valorem Taxes)', originalAmount: 3410, currentBalance: 3410, recordingDate: '2025-11-01', lienType: 'MUNICIPAL_TAX', survivesSale: true, justification: 'Super-priority municipal tax lien' },
        { position: 2, lienHolder: 'Christiana Trust (WSFS) 1st Mortgage', originalAmount: 285000, currentBalance: 298400, recordingDate: '2011-03-18', lienType: 'FIRST_MORTGAGE', survivesSale: false, justification: 'Foreclosing senior plaintiff' },
      ],
      totalSurvivingDebtRequired: 3410,
      safeMaxBidAfterSurvivingDebt: 324590,
    },

    // Build Sequence: Bid Card
    bidCard: {
      caseNumber: 'F-008914-24',
      sheriffNumber: '24001928',
      propertyAddress: '42 Plainfield Ave, Edison, NJ 08817',
      auctionDateTime: 'Wednesday, September 23, 2026 at 1:30 PM',
      sheriffSaleLocation: 'Middlesex County Administration Building, 75 Bayard St, New Brunswick, NJ',
      requiredDepositPercent: 20,
      requiredDepositDollars: 64918,
      openingBid: 1000,
      plaintiffUpsetLimit: 280000,
      ceilingBidHardStop: 324590,
      checklist: [
        { item: 'Bring 20% certified check ($64,918) payable to "Middlesex County Sheriff"', checked: true },
        { item: 'Auction is peremptory — all defendant statutory adjournments exhausted', checked: true },
        { item: 'Vacant property — immediate possession upon 10-day deed delivery without eviction writ', checked: true },
      ],
    },
  },

  // 3. Philadelphia County, PA (Phase 2-4: OPA Open Data & FJD Sheriff)
  {
    id: 'sgs-pa-philly-2026-nov-01842',
    caseNumber: 'NOV TERM 2024 NO. 01842',
    sheriffNumber: 'PH-26-0819',
    saleType: 'sheriff_foreclosure',
    jurisdictionState: 'PA',
    county: 'Philadelphia County, PA',
    court: 'Court of Common Pleas, First Judicial District of Pennsylvania',
    auctionDate: '2026-10-06',
    auctionTime: '10:00 AM EDT',
    auctionPlatform: 'Bid4Assets / Philadelphia Sheriff Real Estate Auction',
    auctionUrl: 'https://www.bid4assets.com/philadelphia',
    depositRequirement: '10% electronic deposit via Bid4Assets escrow prior to bidding; balance due in 30 calendar days (Pa.R.C.P. 3135)',
    depositPercent: 10,
    parcel: {
      address: '1428 N 29th St',
      city: 'Philadelphia',
      state: 'PA',
      zip: '19121',
      coordinates: [-75.1834, 39.9792],
      livingSqft: 1680,
      bedrooms: 3,
      bathrooms: 1.5,
      lotSizeAcres: 0.03,
      yearBuilt: 1925,
      propertyType: 'Two-Story Brick Townhouse',
    },
    legalProse: {
      rawNoticeText: `COURT OF COMMON PLEAS OF PHILADELPHIA COUNTY, PENNSYLVANIA. WRIT OF EXECUTION (MORTGAGE FORECLOSURE). DOCKET NO. NOVEMBER TERM 2024 NO. 01842. SHERIFF'S SALE NO. 26-0819. TOWD POINT MORTGAGE TRUST 2019-4, U.S. BANK NATIONAL ASSOCIATION AS INDENTURE TRUSTEE, PLAINTIFF VS. ESTATE OF MARCUS VAUGHN, DEFENDANT. PURSUANT TO PA.R.C.P. 3129.1, NOTICE IS HEREBY GIVEN THAT BY VIRTUE OF SAID WRIT, THE SHERIFF OF PHILADELPHIA COUNTY WILL SELL ONLINE VIA BID4ASSETS.COM ON TUESDAY, OCTOBER 6, 2026 AT 10:00 A.M.: ALL THAT CERTAIN BRICK MESSUAGE AND LOT OF GROUND IN THE 29TH WARD OF THE CITY OF PHILADELPHIA, COMMONLY KNOWN AS 1428 N. 29TH STREET, PHILADELPHIA, PA 19121 (OPA ACCOUNT # 291189400). JUDGMENT AMOUNT: $118,500.00. ATTORNEY ON WRIT: STERN & EISENBERG, PC.`,
      plaintiff: 'TOWD POINT MORTGAGE TRUST 2019-4, U.S. BANK NATIONAL ASSOCIATION AS INDENTURE TRUSTEE',
      defendant: 'ESTATE OF MARCUS VAUGHN',
      caseNumber: 'NOV TERM 2024 NO. 01842',
      courtDocket: 'First Judicial District of PA Court Docket Nov 2024-01842',
      statute: 'Pa.R.C.P. No. 3129.1 & 42 Pa.C.S. § 8152',
      writExecutionDate: '2026-04-29',
      finalJudgmentAmount: 118500,
      statutoryRedemption: {
        periodDays: 0,
        rule: 'In Pennsylvania mortgage foreclosure sales, there is NO statutory post-sale right of redemption for mortgage foreclosure (unlike tax sales). Right terminates at hammer.',
        citation: '42 Pa.C.S. § 8152 (Judicial Sales Discharge)',
        equityProtectionNote: 'No post-sale redemption. Title passes immediately upon Sheriff Deed recording.',
      },
      seniorLiens: {
        delinquentPropertyTaxes: 2180,
        municipalAssessments: 1450,
        codeEnforcementFines: 0,
        seniorMortgageStatus: 'FORECLOSING_SENIOR',
        survivingSeniorAmount: 3630,
        totalSeniorBurden: 3630,
        notes: 'Philadelphia City real estate taxes ($2,180) and Philadelphia Water Department utility lien ($1,450) survive by operation of PA law.',
      },
      titleCloudRisk: 'LOW',
    },
    openData: {
      apn: '291189400',
      countyAppraiserMarketValue: 245000,
      countyAssessedValue: 245000,
      annualAdValoremTax: 3429,
      delinquentTaxYears: [2024, 2025],
      delinquentTaxTotal: 2180,
      lastDeedDate: '2001-08-14',
      lastDeedPrice: 28000,
      deedBookPage: 'Document # 50192841',
      zoningCode: 'RSA-5',
      zoningDescription: 'Residential Single-Family Attached',
      legalLotDescription: '29TH WARD, 1428 N 29TH ST, PHILADELPHIA, PA 19121',
      floodZone: 'Zone X',
      openDataLicense: 'OpenDataPhilly / City of Philadelphia Open Data Policy',
      primaryPortalUrl: 'https://property.phila.gov/?p=291189400',
    },
    openImagery: {
      aerialSource: 'USDA NAIP 0.6m Ortho + OpenDataPhilly Oblique Imagery',
      imageryDate: 'August 2026 Flyover',
      resolutionMeters: 0.6,
      roofWearScore: 74,
      roofType: 'Flat Modified Bitumen Rubber Membrane',
      structuralIntegrityRating: 'MODERATE',
      lotAccessStatus: 'DEDICATED_PUBLIC_ROAD',
      imageryObservations: [
        'Brick front facade with original cornice in intact condition.',
        'Flat roof shows silver coating; minor ponding at rear scupper box.',
        'Adjacent rowhomes fully occupied and renovated.',
      ],
    },
    aiWorkforce: {
      legalProseReader: {
        agentName: 'LexForeclose Legal Counsel AI',
        verdict: 'CLEARED FOR BIDDING: True judicial mortgage sale with no statutory redemption.',
        titleRiskGrade: 'A',
        clearedForBidding: true,
        statutorySummary: 'Clean Pa.R.C.P. 3129.1 title affidavit filed. Philadelphia Water Department lien confirmed at $1,450.',
      },
      openDataCorrelator: {
        agentName: 'Cadastre & Macro Analyst AI',
        submarketMedianArv: 265000,
        submarketPricePerSqft: 157,
        compsAnalyzed: 12,
        assessmentRatio: 1.0,
        taxDelinquencyWarning: 'Philadelphia City tax delinquent balance: $2,180.',
      },
      openImageryInspector: {
        agentName: 'NAIP Computer Vision Aerial Surveyor',
        estimatedCurbAppealRating: 7,
        structuralRiskLevel: 'LOW',
        exteriorRehabMultiplier: 1.15,
        aerialFlags: ['Scupper box cleaning needed', 'Rear yard debris cleanout'],
      },
      dealUnderwriter: {
        agentName: 'Distress Underwriter AI',
        modeledArv: 265000,
        modeledRehabCost: 45000,
        holdingAndClosingCosts: 16500,
        minimumUpsetBid: 75000,
        maximumAllowableBid: 140500,
        expectedGrossProfit: 88000,
        expectedNetMarginPct: 33.2,
        perfectScore: 89,
        riskTier: 'RING_1_PRIORITY',
        executiveSummary: 'Brewerytown / Strawberry Mansion revitalization pocket. Solid brick shell ready for modern 3-bed / 2-bath renovation.',
      },
    },
    outcomesLedger: {
      saleId: 'sgs-pa-philly-2026-nov-01842',
      address: '1428 N 29th St, Philadelphia, PA',
      county: 'Philadelphia County, PA',
      auctionDate: '2026-10-06',
      predictedArv: 265000,
      predictedMaxBid: 140500,
      actualWinningBid: 0,
      variancePct: 0,
      outcome: 'WIN',
      learningFactorApplied: 1.022,
      weeklyCalibrationInsight: 'North Philadelphia rowhome flips registering 18-day average market turnaround when priced sub-$280k.',
    },
    verifiedAugust2026: true,

    // Build Sequence: Entity Resolution (Hack 3)
    entityResolution: {
      rawEntityName: 'TOWD POINT MORTGAGE TRUST 2019-4, U.S. BANK NATIONAL ASSOCIATION AS INDENTURE TRUSTEE',
      trueBeneficialOwner: 'Cerberus Capital Management LP (New York, NY)',
      loanServicer: 'Select Portfolio Servicing, Inc. (SPS - Salt Lake City, UT)',
      plaintiffCounselFirm: 'Stern & Eisenberg, PC (Cherry Hill, NJ / Philadelphia, PA)',
      foreclosureCounselContact: '(856) 667-5400 / serviceNJ@sterneisenberg.com',
    },

    // Build Sequence: Daily Status Capture (Hack 9)
    dailyStatus: {
      currentStatus: 'ACTIVE_SCHEDULED',
      lastStatusCheck: '2026-09-06T08:30:00Z',
      statutoryAdjournmentCount: 0,
      adjournmentHistory: [],
      bankruptcyStayActive: false,
    },

    // Build Sequence: The Four Listing Panels
    compsAndMargin: {
      recentComps: [
        { address: '1416 N 29th St, Philadelphia', saleDate: '2026-07-21', salePrice: 269000, sqft: 1710, pricePerSqft: 157, distanceMiles: 0.05, condition: 'Renovated' },
        { address: '1440 N 28th St, Philadelphia', saleDate: '2026-06-14', salePrice: 258000, sqft: 1650, pricePerSqft: 156, distanceMiles: 0.11, condition: 'Good' },
        { address: '1502 N 30th St, Philadelphia', saleDate: '2026-05-30', salePrice: 275000, sqft: 1720, pricePerSqft: 159, distanceMiles: 0.18, condition: 'Turnkey' },
      ],
      submarketMedianPpsf: 157,
      modeledRehabTier: 'MEDIUM_UPDATE',
      modeledRehabEstimate: 45000,
      holdingAndCarryingCosts: 16500,
      maximumAllowableBid: 140500,
      netSpreadDollars: 88000,
      netMarginPercent: 33.2,
    },

    flipScoreAndEndGame: {
      flipScore: 89,
      estimatedTurnaroundDays: 110,
      fixAndFlipIrr: 34.5,
      brrrrRentalYield: 12.1,
      wholetailMargin: 65000,
      recommendedExitStrategy: 'BRRRR_RENTAL',
      sensitivityMatrix: [
        { discountPct: 40, purchaseBid: 159000, projectedRoi: 35.8 },
        { discountPct: 45, purchaseBid: 145750, projectedRoi: 44.2 },
        { discountPct: 50, purchaseBid: 132500, projectedRoi: 54.0 },
      ],
    },

    resaleDemandMeter: {
      submarketAbsorptionRateMonths: 1.6,
      averageDaysOnMarket: 22,
      buyerLiquidityIndex: 88,
      schoolDistrictRating: 6,
      demandVerdict: 'EXTREME_SELLER_MARKET',
    },

    theCatch: {
      seniorSurvivingLiens: [
        { type: 'Philadelphia City Real Estate Taxes', holder: 'City of Philadelphia Dept of Revenue', amount: 2180, survivesSale: true, legalBasis: '53 P.S. § 7101 (Municipal Tax Priority)' },
        { type: 'Philadelphia Water Department (PWD)', holder: 'Philadelphia Water Department', amount: 1450, survivesSale: true, legalBasis: '53 P.S. § 7106 (Water/Sewer Super-priority)' },
      ],
      municipalTaxCertificate: { hasCertificate: false },
      codeViolations: [],
      irsRedemptionPeriodDays: 0,
      occupancyStatus: 'VACANT_CONFIRMED',
      overallTitleCloudRisk: 'PRISTINE_INSURABLE',
    },

    // Build Sequence: Assisted Lien Check (Hack 8)
    assistedLienCheck: {
      waterfall: [
        { position: 1, lienHolder: 'City of Philadelphia (Taxes & Water)', originalAmount: 3630, currentBalance: 3630, recordingDate: '2025-06-01', lienType: 'MUNICIPAL_TAX', survivesSale: true, justification: 'Municipal lien survives judicial mortgage sale' },
        { position: 2, lienHolder: 'Towd Point Mortgage Trust (Cerberus) 1st Mortgage', originalAmount: 115000, currentBalance: 118500, recordingDate: '2001-08-14', lienType: 'FIRST_MORTGAGE', survivesSale: false, justification: 'Foreclosing senior lien' },
      ],
      totalSurvivingDebtRequired: 3630,
      safeMaxBidAfterSurvivingDebt: 136870,
    },

    // Build Sequence: Bid Card
    bidCard: {
      caseNumber: 'NOV TERM 2024 NO. 01842',
      sheriffNumber: 'PH-26-0819',
      propertyAddress: '1428 N 29th St, Philadelphia, PA 19121',
      auctionDateTime: 'Tuesday, October 6, 2026 at 10:00 AM',
      sheriffSaleLocation: 'Online via Bid4Assets.com (Philadelphia Sheriff Real Estate)',
      requiredDepositPercent: 10,
      requiredDepositDollars: 13687,
      openingBid: 800,
      plaintiffUpsetLimit: 110000,
      ceilingBidHardStop: 136870,
      checklist: [
        { item: 'Fund Bid4Assets account with 10% minimum deposit ($13,687) by Monday 5:00 PM', checked: true },
        { item: 'No post-sale redemption under PA law — clear title delivered in 30 days', checked: true },
        { item: 'Budget $3,630 for surviving PWD water and City of Philadelphia municipal taxes', checked: true },
      ],
    },
  },

  // 4. Allegheny County, PA (Pittsburgh WPRDC / Hack 12 Realized Margin Tracking)
  {
    id: 'sgs-pa-allegheny-gd-24-009182',
    caseNumber: 'GD-24-009182',
    sheriffNumber: 'AL-26-0412',
    saleType: 'sheriff_foreclosure',
    jurisdictionState: 'PA',
    county: 'Allegheny County, PA',
    court: 'Court of Common Pleas of Allegheny County, Pennsylvania',
    auctionDate: '2026-07-06',
    auctionTime: '9:00 AM EDT',
    auctionPlatform: 'Allegheny County Sheriff Auction / Gold Room',
    auctionUrl: 'https://sheriffalleghenycounty.com/real_estate.html',
    depositRequirement: '$2,000 or 10% certified check immediately; balance in 10 calendar days',
    depositPercent: 10,
    parcel: {
      address: '4812 Cypress St',
      city: 'Pittsburgh',
      state: 'PA',
      zip: '15224',
      coordinates: [-79.9452, 40.4619],
      livingSqft: 1820,
      bedrooms: 3,
      bathrooms: 2,
      lotSizeAcres: 0.05,
      yearBuilt: 1910,
      propertyType: 'Two-Story Victorian Brick Duplex/Single',
    },
    legalProse: {
      rawNoticeText: `COURT OF COMMON PLEAS OF ALLEGHENY COUNTY, CIVIL DIVISION. DOCKET GD-24-009182. DEUTSCHE BANK NATIONAL TRUST COMPANY AS TRUSTEE FOR GSAMP TRUST 2006-HE3, PLAINTIFF VS. ESTATE OF ROBERT KLINE, DEFENDANT. WRIT OF EXECUTION (MORTGAGE FORECLOSURE). SALE OF REAL ESTATE AT PUBLIC AUCTION IN THE GOLD ROOM, 4TH FLOOR, ALLEGHENY COUNTY COURTHOUSE, PITTSBURGH, PA: ALL THAT CERTAIN LOT OF GROUND SITUATE IN THE 8TH WARD OF THE CITY OF PITTSBURGH, COMMONLY KNOWN AS 4812 CYPRESS STREET, PITTSBURGH, PA 15224 (BLOCK & LOT 0052-G-00124). JUDGMENT AMOUNT: $94,200.00. ATTORNEY ON WRIT: KML LAW GROUP, P.C.`,
      plaintiff: 'DEUTSCHE BANK NATIONAL TRUST COMPANY AS TRUSTEE FOR GSAMP TRUST 2006-HE3',
      defendant: 'ESTATE OF ROBERT KLINE',
      caseNumber: 'GD-24-009182',
      courtDocket: 'Allegheny County Prothonotary Docket GD-24-009182',
      statute: 'Pa.R.C.P. 3129 & WPRDC Real Estate Integration',
      writExecutionDate: '2026-03-12',
      finalJudgmentAmount: 94200,
      statutoryRedemption: {
        periodDays: 0,
        rule: 'No statutory redemption period in PA mortgage foreclosure.',
        citation: '42 Pa.C.S. § 8152',
        equityProtectionNote: 'Auction completed. Deed recorded in Allegheny County Department of Real Estate.',
      },
      seniorLiens: {
        delinquentPropertyTaxes: 1890,
        municipalAssessments: 0,
        codeEnforcementFines: 0,
        seniorMortgageStatus: 'FORECLOSING_SENIOR',
        survivingSeniorAmount: 1890,
        totalSeniorBurden: 1890,
        notes: 'Delinquent City/School/County taxes satisfied at closing.',
      },
      titleCloudRisk: 'LOW',
    },
    openData: {
      apn: '0052-G-00124-0000-00',
      countyAppraiserMarketValue: 310000,
      countyAssessedValue: 245000,
      annualAdValoremTax: 5120,
      delinquentTaxYears: [2024],
      delinquentTaxTotal: 1890,
      lastDeedDate: '2026-07-28',
      lastDeedPrice: 112000,
      deedBookPage: 'Deed Book 19482, Page 291',
      zoningCode: 'R2-H',
      zoningDescription: 'Two-Unit Residential High Density',
      legalLotDescription: '8TH WARD, 4812 CYPRESS ST, PITTSBURGH, PA 15224',
      floodZone: 'Zone X',
      openDataLicense: 'Western Pennsylvania Regional Data Center (WPRDC) Open Commons',
      primaryPortalUrl: 'https://data.wprdc.org',
    },
    openImagery: {
      aerialSource: 'USDA NAIP 0.6m High-Res Multi-Spectral Ortho',
      imageryDate: 'August 2026 Flyover',
      resolutionMeters: 0.6,
      roofWearScore: 80,
      roofType: 'Slate and Asphalt Composite',
      structuralIntegrityRating: 'EXCELLENT',
      lotAccessStatus: 'DEDICATED_PUBLIC_ROAD',
      imageryObservations: [
        'Victorian brickwork repointed on facade.',
        'High-density Bloomfield / Lawrenceville residential block with substantial organic appreciation.',
      ],
    },
    aiWorkforce: {
      legalProseReader: {
        agentName: 'LexForeclose Legal Counsel AI',
        verdict: 'CLOSED & RECORDED: Successfully acquired at auction by third-party investor.',
        titleRiskGrade: 'A',
        clearedForBidding: true,
        statutorySummary: 'Deed confirmed and transferred to acquisition entity. Clean title warranty.',
      },
      openDataCorrelator: {
        agentName: 'Cadastre & Macro Analyst AI',
        submarketMedianArv: 345000,
        submarketPricePerSqft: 190,
        compsAnalyzed: 14,
        assessmentRatio: 0.79,
        taxDelinquencyWarning: 'All municipal liabilities cleared on settlement sheet.',
      },
      openImageryInspector: {
        agentName: 'NAIP Computer Vision Aerial Surveyor',
        estimatedCurbAppealRating: 9,
        structuralRiskLevel: 'LOW',
        exteriorRehabMultiplier: 1.0,
        aerialFlags: ['Completed full interior modernization'],
      },
      dealUnderwriter: {
        agentName: 'Distress Underwriter AI',
        modeledArv: 345000,
        modeledRehabCost: 48000,
        holdingAndClosingCosts: 18500,
        minimumUpsetBid: 85000,
        maximumAllowableBid: 175000,
        expectedGrossProfit: 139000,
        expectedNetMarginPct: 40.3,
        perfectScore: 96,
        riskTier: 'RING_1_PRIORITY',
        executiveSummary: 'Bloomfield / Childrens Hospital healthcare corridor. Purchased for $112k at auction, rehabbed for $48k, arms-length resale closed for $348,000.',
      },
    },
    outcomesLedger: {
      saleId: 'sgs-pa-allegheny-gd-24-009182',
      address: '4812 Cypress St, Pittsburgh, PA',
      county: 'Allegheny County, PA',
      auctionDate: '2026-07-06',
      predictedArv: 345000,
      predictedMaxBid: 175000,
      actualWinningBid: 112000,
      actualResaleDeedPrice: 348000,
      actualResaleDate: '2026-08-28',
      variancePct: 0.87,
      outcome: 'WIN',
      learningFactorApplied: 1.008,
      weeklyCalibrationInsight: 'Prediction was within 0.87% of actual arms-length sale ($348k vs $345k predicted). Ledger calibrated +0.8%.',
    },
    verifiedAugust2026: true,

    // Build Sequence: Entity Resolution (Hack 3)
    entityResolution: {
      rawEntityName: 'DEUTSCHE BANK NATIONAL TRUST COMPANY AS TRUSTEE FOR GSAMP TRUST 2006-HE3',
      trueBeneficialOwner: 'Goldman Sachs Mortgage Co / Alternative Assets',
      loanServicer: 'PHH Mortgage Corporation / Onity Group',
      plaintiffCounselFirm: 'KML Law Group, P.C. (Philadelphia, PA)',
      foreclosureCounselContact: '(856) 651-3000 / pleadings@kmllawgroup.com',
    },

    // Build Sequence: Daily Status Capture (Hack 9)
    dailyStatus: {
      currentStatus: 'SOLD_THIRD_PARTY',
      lastStatusCheck: '2026-08-28T12:00:00Z',
      statutoryAdjournmentCount: 0,
      adjournmentHistory: [],
      bankruptcyStayActive: false,
    },

    // Build Sequence: The Four Listing Panels
    compsAndMargin: {
      recentComps: [
        { address: '4820 Cypress St, Pittsburgh', saleDate: '2026-08-15', salePrice: 352000, sqft: 1840, pricePerSqft: 191, distanceMiles: 0.04, condition: 'Renovated' },
        { address: '4731 Liberty Ave, Pittsburgh', saleDate: '2026-07-29', salePrice: 341000, sqft: 1790, pricePerSqft: 190, distanceMiles: 0.15, condition: 'Good' },
      ],
      submarketMedianPpsf: 190,
      modeledRehabTier: 'MEDIUM_UPDATE',
      modeledRehabEstimate: 48000,
      holdingAndCarryingCosts: 18500,
      maximumAllowableBid: 175000,
      netSpreadDollars: 169500,
      netMarginPercent: 49.1,
    },

    flipScoreAndEndGame: {
      flipScore: 96,
      estimatedTurnaroundDays: 52,
      fixAndFlipIrr: 68.2,
      brrrrRentalYield: 14.2,
      wholetailMargin: 120000,
      recommendedExitStrategy: 'FIX_AND_FLIP',
      sensitivityMatrix: [
        { discountPct: 50, purchaseBid: 172500, projectedRoi: 48.0 },
        { discountPct: 60, purchaseBid: 138000, projectedRoi: 64.2 },
        { discountPct: 67, purchaseBid: 112000, projectedRoi: 82.5 },
      ],
    },

    resaleDemandMeter: {
      submarketAbsorptionRateMonths: 1.1,
      averageDaysOnMarket: 9,
      buyerLiquidityIndex: 98,
      schoolDistrictRating: 7,
      demandVerdict: 'EXTREME_SELLER_MARKET',
    },

    theCatch: {
      seniorSurvivingLiens: [
        { type: 'Allegheny County & City Property Taxes', holder: 'Treasurer of Allegheny County', amount: 1890, survivesSale: true, legalBasis: 'PA Title 53 § 7101' },
      ],
      municipalTaxCertificate: { hasCertificate: false },
      codeViolations: [],
      irsRedemptionPeriodDays: 0,
      occupancyStatus: 'VACANT_CONFIRMED',
      overallTitleCloudRisk: 'PRISTINE_INSURABLE',
    },

    // Build Sequence: Assisted Lien Check (Hack 8)
    assistedLienCheck: {
      waterfall: [
        { position: 1, lienHolder: 'Allegheny County / City of Pittsburgh Taxes', originalAmount: 1890, currentBalance: 1890, recordingDate: '2024-12-01', lienType: 'MUNICIPAL_TAX', survivesSale: true, justification: 'Senior real estate tax lien' },
        { position: 2, lienHolder: 'GSAMP Trust 2006-HE3 1st Mortgage', originalAmount: 92000, currentBalance: 94200, recordingDate: '2006-04-12', lienType: 'FIRST_MORTGAGE', survivesSale: false, justification: 'Foreclosing senior mortgage' },
      ],
      totalSurvivingDebtRequired: 1890,
      safeMaxBidAfterSurvivingDebt: 173110,
    },

    // Build Sequence: Bid Card
    bidCard: {
      caseNumber: 'GD-24-009182',
      sheriffNumber: 'AL-26-0412',
      propertyAddress: '4812 Cypress St, Pittsburgh, PA 15224',
      auctionDateTime: 'Monday, July 6, 2026 at 9:00 AM',
      sheriffSaleLocation: 'Allegheny County Courthouse, Gold Room, 436 Grant St, Pittsburgh, PA',
      requiredDepositPercent: 10,
      requiredDepositDollars: 11200,
      openingBid: 800,
      plaintiffUpsetLimit: 95000,
      ceilingBidHardStop: 173110,
      checklist: [
        { item: 'Bring $2,000 or 10% certified check to the Gold Room', checked: true },
        { item: 'Deed settlement due by following Friday at 10:00 AM', checked: true },
        { item: 'WPRDC parcel verification confirmed', checked: true },
      ],
    },

    // Build Sequence: Realized Margin Tracking (Hack 12)
    realizedMargin: {
      auctionWinningBid: 112000,
      winningBidderType: 'THIRD_PARTY_INVESTOR',
      sheriffDeedRecordingDate: '2026-07-28',
      armsLengthFlipDate: '2026-08-28',
      armsLengthFlipPrice: 348000,
      grossRealizedSpread: 188000, // 348k - (112k purchase + 48k rehab)
      realizedHoldDays: 52,
      realizedAnnualizedIrr: 68.2,
    },
  },
];
