export { Header } from './Header'
export { Hero } from './Hero'
export { SocialProof } from './SocialProof'
export { Storyteller } from './Storyteller'
export { MarketContext, MarketContext as AIKnows } from './MarketContext'
export { Features, Features as FastestWay } from './Features'
export { GTMSection } from './GTMSection'
export { IntegrationBar } from './IntegrationBar'
export { CTASection } from './CTASection'
export { Footer } from './Footer'
export { LandingPage } from './LandingPage'
export { TailarkHero } from './TailarkHero'
export { TailarkIntegrations } from './TailarkIntegrations'
export { TailarkBentoFeatures } from './TailarkBentoFeatures'
export { TailarkInteractiveTerminal } from './TailarkInteractiveTerminal'
export { TailarkTestimonials } from './TailarkTestimonials'
export { TailarkCTA } from './TailarkCTA'
export { TailarkFooter } from './TailarkFooter'
export { default as HeroSection2, HeroSection2 as TailarkHeroSection2 } from '@/components/hero-section-2'
